language: julia
julia:
  - 0.6
env:
  - TEST_DIR=Project4/julia/test
git:
  submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
script: cd $TEST_DIR && julia --code-coverage test.jl
# Coverage.jl
after_success:
    - julia -e 'println(pwd()); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder("."))'

